version: '3.8'

services:
  postgres:
    container_name: "postgres-container"
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: myDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust  # Bağlantı için 'trust' kullan
    ports:
      - '5432:5432'

  pgadmin:
    container_name: "pgadmin-container"
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5051:80'  # pgAdmin varsayılan olarak 80 portunu kullanır, dışarıya 5051 portunu açıyoruz

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "spring-boot-app"
    ports:
      - "8080:8080"  # Uygulamanızın dinlediği port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/myDb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
